experiment:
  epochs: 5000
  max_turns: 50
  record_period: 50
  mode: bush
  zero_emotion_after_training: false # Set true to freeze the model and evaluate with the emotion layer zeroed.
  zero_emotion_eval_epochs: 0        # Number of evaluation epochs to run when zeroing the emotion layer.
        
model: 
  agent_vision_radius: 3
  emotion_condition: full # Options: ["full", "self", "other", "none"]
  epsilon_decay: 0.0001

world:
  agents: 10
  wolves: 3
  height: 25
  width: 25
  spawn_prob: 0.001
  bush_lifespan: 30
